### ISSUE TITLE
Broken links to the libre office tables 

### ISSUE THREAD

**Issue by Samsemilio** [duniter/Geconomicus#23]
The following links are broken:
Cliquer ici pour télécharger le tableur LibreOffice du compte-rendu
Cliquer ici pour télécharger le tableur LibreOffice du banquier

**Comment by galuel** [comment]
Ok, thx we will fix it :)

**Comment by vtexier** [comment]
In the meantime, you can have working links here : http://vtexier.github.io/Geconomicus/
