### ISSUE TITLE
Move this repository to a new organization

### ISSUE THREAD

**Issue by M5oul** [duniter/Geconomicus#25]
We could create an organization for libre currency projects
How do you want to call this organization?
I propose https://github.com/libre-currency-projects

**Comment by vtexier** [comment]
I prefer to use the generic term of "money". "Currency" is right, but more specific to one currency.

Like you, I don't like the "free" term and prefer "libre".
So may be "libre-money-projects" ?

What do you think of it?

**Comment by M5oul** [comment]
It's ok for me.

**Comment by galuel** [comment]
Moved in Duniter project
