### ISSUE TITLE
Nbre de cartes en fonction du nombre de joueurs

### ISSUE THREAD

**Issue by paidge** [duniter/Geconomicus#26]
Avec la v1.0 de Geconomicus, il fallait 5 x nbre de joueurs en nombre de cartes.
Avec la v2.0, vu qu'il faut 4 couleurs de cartes pour les valeurs. Donc il faut 4 fois plus de cartes. Il en faut donc désormais 20 x le nbre de joueurs.
On peut le dire peut-être plus clairement en disant :
Il faut 4 paquets de (5*nbre de joueurs) cartes.

**Comment by galuel** [comment]
Fait en version 2.1
